# Generated by Django 5.1.1 on 2024-10-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0003_superhero_author_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="superhero",
            name="id",
        ),
        migrations.AddField(
            model_name="superhero",
            name="new_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
