# Generated by Django 5.1.1 on 2024-10-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0004_remove_superhero_id_superhero_new_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="superhero",
            name="author",
        ),
        migrations.RemoveField(
            model_name="superhero",
            name="new_id",
        ),
        migrations.AddField(
            model_name="superhero",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
